In [10]:
import numpy as np
import pandas as pd
from pathlib import Path

In [3]:
df = pd.read_csv('border.csv')

In [4]:
df.head(3)

,Port Name,State,Port Code,Border,Date,Measure,Value,Latitude,Longitude,Point
0,Jackman,Maine,104,US-Canada Border,Jan 2024,Trucks,6556,45.806,-70.397,POINT (-70.396722 45.805661)
1,Porthill,Idaho,3308,US-Canada Border,Apr 2024,Trucks,98,49.000,-116.499,POINT (-116.49925 48.999861)
2,San Luis,Arizona,2608,US-Mexico Border,Apr 2024,Buses,10,32.485,-114.782,POINT (-114.7822222 32.485)

In [8]:
df.tail(2)

,Port Name,State,Port Code,Border,Date,Measure,Value,Latitude,Longitude,Point
403855,El Paso,Texas,2402,US-Mexico Border,Aug 2025,Trains,125,31.764,-106.451,POINT (-106.451188 31.764363)
403856,Calais,Maine,115,US-Canada Border,Aug 2025,Trucks,5019,45.189,-67.275,POINT (-67.275381 45.188548)

In [7]:
df=df.drop_duplicates()

In [19]:
df.isnull().sum()

port_name    0
state        4
port_code    0
border       0
date         0
measure      0
value        0
latitude     4
longitude    4
point        4
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df = df.drop_duplicates()

In [22]:
df.rename(columns={
    'Port Name': 'port_name',
    'State': 'state',
    'Port Code': 'port_code',
    'Border': 'border',
    'Date': 'date',
    'Measure': 'measure',
    'Value': 'value',
    'Latitude': 'latitude',
    'Longitude': 'longitude',
    'Point': 'point'
}, inplace=True)

In [23]:
df['date'] = pd.to_datetime(df['date'], format='%b %Y', errors='coerce')

In [24]:
df = df.dropna(subset=['date'])

In [25]:
df['port_code'] = pd.to_numeric(df['port_code'], errors='coerce').fillna(0).astype(int)
df['value'] = pd.to_numeric(df['value'], errors='coerce').fillna(0).astype(int)
df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

In [26]:
df = df[['port_name', 'state', 'port_code', 'border', 'date', 'measure', 'value', 'latitude', 'longitude', 'point']]

In [29]:
df.to_csv('border_cleaned.csv', index=False)